# Generated by Django 4.0.1 on 2022-02-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_order_products_orderbasketproduc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderBasketProduc',
            new_name='OrderBasketProduct',
        ),
    ]
